apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-credentials
  namespace: postgres
type: Opaque
stringData:
  ACCESS_KEY_ID: "postgres-backup"
  ACCESS_SECRET_KEY: "postgres-backup-secret-key-change-me"
