apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: argo-events-role
rules:
- apiGroups: [ "argoproj.io" ]
  resources: [ "workflows", "workflowtemplates", "workfloweventbindings", "workflowtaskresults" ]
  verbs: [ "create", "get", "list", "watch", "update", "patch", "delete" ]
- apiGroups: [ "" ]
  resources: [ "pods", "pods/log", "serviceaccounts" ]
  verbs: [ "create", "get", "list", "watch", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-kubectl-cluster-role
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "pods/log" ]
  verbs: [ "create", "get", "list", "watch", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-kubectl-cluster-binding
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: argo
- kind: ServiceAccount
  name: default
  namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-kubectl-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: argo
- kind: ServiceAccount
  name: default
  namespace: argo
roleRef:
  kind: Role
  name: argo-events-role
  apiGroup: rbac.authorization.k8s.io
