apiVersion: v1
kind: Service
metadata:
  name: webhook-eventsource-svc
  namespace: argo
  labels:
    app: webhook-eventsource
spec:
  selector:
    app: webhook-eventsource
  ports:
  - name: webhook
    port: 12000
    targetPort: 12000
    protocol: TCP
  type: ClusterIP
